/** @type {import('tailwindcss').Config} */
import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#38485a',
        'surface-variant': '#e2e8f0',
        'surface-container-lowest': '#ffffff',
        'on-tertiary-container': '#f0fdfa',
        'secondary-fixed': '#dbeafe',
        'on-primary-fixed-variant': '#1e40af',
        'on-secondary-fixed': '#0f172a',
        'error-container': '#fee2e2',
        primary: '#2563eb',
        'primary-fixed-dim': '#bfdbfe',
        'on-tertiary-fixed-variant': '#115e59',
        'inverse-surface': '#172033',
        outline: '#64748b',
        'inverse-on-surface': '#f8fafc',
        'tertiary-fixed': '#99f6e4',
        tertiary: '#0f766e',
        'primary-container': '#1d4ed8',
        'on-background': '#0f172a',
        'primary-fixed': '#dbeafe',
        'on-secondary-container': '#475569',
        'secondary-fixed-dim': '#cbd5e1',
        'on-error-container': '#991b1b',
        'on-secondary': '#ffffff',
        'outline-variant': '#cbd5e1',
        'surface-container-low': '#f1f5f9',
        'on-error': '#ffffff',
        'on-primary-container': '#ffffff',
        secondary: '#475569',
        'surface-tint': '#2563eb',
        background: '#f4f7fb',
        'surface-container': '#e9eff7',
        surface: '#ffffff',
        'secondary-container': '#dbeafe',
        'on-surface': '#0f172a',
        'surface-bright': '#ffffff',
        'surface-container-highest': '#dbe4f0',
        'on-primary': '#ffffff',
        'tertiary-fixed-dim': '#5eead4',
        'inverse-primary': '#93c5fd',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#0f766e',
        'on-tertiary-fixed': '#042f2e',
        'surface-dim': '#dbe4f0',
        'on-primary-fixed': '#172554',
        error: '#dc2626',
        'surface-container-high': '#e2e8f0',
        'on-surface-variant': '#475569',
      },
      borderRadius: { DEFAULT: '0.375rem', lg: '0.625rem', xl: '0.875rem', full: '9999px' },
      spacing: { md: '16px', 'container-margin': '24px', xs: '4px', xl: '32px', sm: '8px', lg: '24px', gutter: '16px', base: '4px' },
      fontFamily: {
        'nav-item': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'nav-item': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
    },
  },
  plugins: [forms, containerQueries],
};
