import { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import CompanyShell from '../../../components/company/CompanyShell';
import api, { getActiveSessionToken } from '../../../services/api';

export default function CompanyReviews() {
  const [reviews, setReviews] = useState([]); const [query, setQuery] = useState(''); const [drafts, setDrafts] = useState({}); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const result = await api.get('/reviews', { noCache: true }); setReviews(result.reviews || []); } catch (requestError) { setError(requestError.message); } }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const socket = io(import.meta.env.VITE_API_URL || 'http://localhost:5000', { withCredentials: true, auth: { token: getActiveSessionToken() }, transports: ['websocket', 'polling'] }); socket.on('review:created', load); socket.on('review:updated', load); return () => socket.disconnect(); }, [load]);
  const filtered = useMemo(() => reviews.filter((review) => [review.customer?.name, review.booking?.serviceSnapshot?.name, review.comment].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [reviews, query]);
  const reply = async (review) => { const text = String(drafts[review._id] || '').trim(); if (!text) return; try { await api.put(`/reviews/${review._id}/reply`, { reply: text }); setDrafts((current) => ({ ...current, [review._id]: '' })); await load(); } catch (requestError) { setError(requestError.message); } };
  return <CompanyShell title="Reviews" subtitle="Client feedback is saved with the completed booking and updates here in real time." search={query} onSearch={setQuery}>
    {error && <p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <section className="grid gap-5 xl:grid-cols-2">{filtered.map((review) => <article key={review._id} className="rounded-3xl border border-slate-100 bg-white p-6 shadow-sm"><div className="flex items-start justify-between gap-4"><div><h2 className="font-bold text-slate-900">{review.customer?.name || 'Client'}</h2><p className="mt-1 text-sm text-slate-500">{review.booking?.serviceSnapshot?.name || 'Completed company request'}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-sm font-bold text-amber-700">★ {review.rating}/5</span></div><p className="mt-5 leading-7 text-slate-700">{review.comment || 'No written feedback.'}</p>{review.reply?.text ? <div className="mt-5 rounded-2xl bg-slate-50 p-4"><p className="text-xs font-bold uppercase tracking-wide text-slate-400">Your reply</p><p className="mt-2 text-sm leading-6 text-slate-700">{review.reply.text}</p></div> : <div className="mt-5 flex gap-2"><input value={drafts[review._id] || ''} onChange={(event) => setDrafts((current) => ({ ...current, [review._id]: event.target.value }))} placeholder="Write a professional reply" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2 text-sm" /><button onClick={() => reply(review)} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-bold text-white">Reply</button></div>}</article>)}{!filtered.length && <p className="rounded-3xl border border-dashed border-slate-200 bg-white p-10 text-center text-slate-500 xl:col-span-2">No reviews match this view yet.</p>}</section>
  </CompanyShell>;
}
