import { useCallback, useEffect, useMemo, useState } from 'react';
import { io } from 'socket.io-client';
import CompanyShell from '../../../components/company/CompanyShell';
import api, { getActiveSessionToken } from '../../../services/api';

const nextStatus = { Assigned: 'En Route', 'En Route': 'Arrived', Arrived: 'In Progress', 'In Progress': 'Completed' };
const formatMoney = (value) => `PKR ${Number(value || 0).toLocaleString('en-PK')}`;

export default function CompanyBookings() {
  const [bookings, setBookings] = useState([]); const [staff, setStaff] = useState([]); const [query, setQuery] = useState(''); const [filter, setFilter] = useState('All'); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [bookingResult, staffResult] = await Promise.all([api.get('/bookings', { noCache: true }), api.get('/technicians', { noCache: true })]); setBookings(bookingResult.bookings || []); setStaff(staffResult.technicians || []); } catch (requestError) { setError(requestError.message); } }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  useEffect(() => { const socket = io(import.meta.env.VITE_API_URL || 'http://localhost:5000', { withCredentials: true, auth: { token: getActiveSessionToken() }, transports: ['websocket', 'polling'] }); socket.on('booking:created', load); socket.on('booking:updated', load); return () => socket.disconnect(); }, [load]);
  const filtered = useMemo(() => bookings.filter((booking) => (filter === 'All' || booking.status === filter) && [booking.reference, booking.customerName, booking.serviceSnapshot?.name, booking.status].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [bookings, filter, query]);
  const assign = async (booking, technicianId) => { if (!technicianId) return; try { await api.post(`/bookings/${booking._id}/assign`, { technicianId }); await load(); } catch (requestError) { setError(requestError.message); } };
  const advance = async (booking) => { const status = nextStatus[booking.status]; if (!status) return; try { await api.put(`/bookings/${booking._id}`, { status }); await load(); } catch (requestError) { setError(requestError.message); } };
  const cancel = async (booking) => { const reason = window.prompt('Cancellation reason'); if (!reason?.trim()) return; try { await api.put(`/bookings/${booking._id}`, { status: 'Cancelled', reason: reason.trim() }); await load(); } catch (requestError) { setError(requestError.message); } };
  return <CompanyShell title="Requests" subtitle="Client bookings appear here immediately. Assign staff and update progress from one consistent workspace." search={query} onSearch={setQuery}>
    {error && <p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <div className="mb-5 flex flex-wrap gap-2">{['All', 'Pending', 'Assigned', 'En Route', 'Arrived', 'In Progress', 'Completed', 'Paid', 'Cancelled'].map((status) => <button key={status} onClick={() => setFilter(status)} className={`rounded-full px-3 py-2 text-xs font-bold ${filter === status ? 'bg-[#0D1B2A] text-white' : 'bg-white text-slate-600 shadow-sm hover:bg-slate-100'}`}>{status}</button>)}</div>
    <section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Client request</th><th className="p-4">Schedule</th><th className="p-4">Status</th><th className="p-4">Assigned staff</th><th className="p-4 text-right">Next action</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((booking) => <tr key={booking._id}><td className="p-4"><b className="text-slate-900">{booking.customerName}</b><small className="mt-1 block font-mono text-slate-400">{booking.reference}</small><p className="mt-1 text-slate-500">{booking.serviceSnapshot?.name || 'Client request'}</p></td><td className="p-4 text-slate-600">{booking.scheduledAt ? new Date(booking.scheduledAt).toLocaleString('en-PK') : 'Not scheduled'}<small className="mt-1 block max-w-xs truncate text-slate-400">{booking.location || 'No location'}</small></td><td className="p-4"><span className="rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700">{booking.status}</span><small className="mt-2 block font-bold text-slate-700">{formatMoney(booking.pricing?.finalTotal)}</small></td><td className="p-4"><select value={booking.technician?._id || ''} disabled={!['Pending', 'Assigned'].includes(booking.status)} onChange={(event) => assign(booking, event.target.value)} className="max-w-[180px] rounded-xl border border-slate-200 bg-white p-2 text-xs font-semibold text-slate-700 disabled:bg-slate-50"><option value="">{booking.technician?.name || 'Assign staff'}</option>{staff.filter((person) => person.status === 'Available' || person._id === booking.technician?._id).map((person) => <option key={person._id} value={person._id}>{person.name}</option>)}</select></td><td className="p-4"><div className="flex justify-end gap-2">{nextStatus[booking.status] && <button onClick={() => advance(booking)} className="rounded-xl bg-blue-600 px-3 py-2 text-xs font-bold text-white hover:bg-blue-700">Mark {nextStatus[booking.status]}</button>}{!['Completed', 'Paid', 'Cancelled'].includes(booking.status) && <button onClick={() => cancel(booking)} className="rounded-xl px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50">Cancel</button>}</div></td></tr>)}{!filtered.length && <tr><td colSpan="5" className="p-12 text-center text-slate-500">No client requests match this view.</td></tr>}</tbody></table></div></section>
  </CompanyShell>;
}
