import { useCallback, useEffect, useMemo, useState } from 'react';
import CompanyShell from '../../../components/company/CompanyShell';
import api from '../../../services/api';

const emptyItem = (category = '') => ({ name: '', category, qty: 0, threshold: 5, unitCost: 0, unitPrice: 0, unit: 'Units' });
const money = (value) => `PKR ${Number(value || 0).toLocaleString('en-PK')}`;

function ItemDialog({ item, categories, workspace, onClose, onSave }) {
  const [form, setForm] = useState(item ? { ...item, qty: item.qty ?? item.quantity, threshold: item.threshold ?? item.reorderLevel } : emptyItem(categories[0] || ''));
  const [customCategory, setCustomCategory] = useState('');
  const update = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const submit = (event) => { event.preventDefault(); onSave({ ...form, category: customCategory.trim() || form.category }); };
  return <div className="fixed inset-0 z-[70] overflow-y-auto bg-slate-950/40 p-3 sm:p-6"><div className="flex min-h-full items-center justify-center"><form onSubmit={submit} className="my-auto w-full max-w-2xl max-h-[calc(100dvh-1.5rem)] overflow-y-auto rounded-3xl bg-white p-5 shadow-2xl sm:max-h-[calc(100dvh-3rem)] sm:p-6">
    <div className="mb-5 flex items-start justify-between gap-4"><div><h2 className="text-xl font-bold text-slate-900">{item ? 'Edit item' : `Add ${workspace.inventoryLabel || 'item'}`}</h2><p className="mt-1 text-sm text-slate-500">This record belongs only to your company and is immediately available to its services.</p></div><button type="button" onClick={onClose} className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-slate-100 text-slate-600 hover:bg-slate-200" aria-label="Close item form">✕</button></div>
    <div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-bold text-slate-700">Item name<input required value={form.name} onChange={(event) => update('name', event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Category<select value={form.category} onChange={(event) => { update('category', event.target.value); setCustomCategory(''); }} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"><option value="">Choose category</option>{categories.map((option) => <option key={option} value={option}>{option}</option>)}</select></label><label className="text-sm font-bold text-slate-700">Or new category<input value={customCategory} onChange={(event) => setCustomCategory(event.target.value)} placeholder="Business-specific category" className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label>{[['qty', 'Quantity'], ['threshold', 'Low-stock alert'], ['unitCost', 'Unit cost (PKR)'], ['unitPrice', 'Client price (PKR)']].map(([key, label]) => <label key={key} className="text-sm font-bold text-slate-700">{label}<input type="number" min="0" required value={form[key]} onChange={(event) => update(key, Number(event.target.value))} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label>)}<label className="text-sm font-bold text-slate-700">Unit<input value={form.unit} onChange={(event) => update('unit', event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label></div>
    <div className="mt-6 flex flex-col-reverse gap-3 border-t border-slate-100 pt-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="rounded-xl px-4 py-3 font-bold text-slate-600 hover:bg-slate-100">Cancel</button><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white hover:bg-blue-700">Save item</button></div>
  </form></div></div>;
}

export default function CompanyInventory() {
  const [items, setItems] = useState([]); const [services, setServices] = useState([]); const [company, setCompany] = useState(null); const [query, setQuery] = useState(''); const [category, setCategory] = useState('All'); const [editing, setEditing] = useState(null); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [inventoryResult, servicesResult, dashboardResult] = await Promise.all([api.get('/inventory', { noCache: true }), api.get('/services', { noCache: true }), api.get('/company/dashboard', { noCache: true })]); setItems(inventoryResult.inventory || []); setServices(servicesResult.services || []); setCompany(dashboardResult.company || null); } catch (requestError) { setError(requestError.message); } }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  const workspace = company?.workspace || {};
  const categoryOptions = useMemo(() => [...new Set([...(workspace.inventoryCategories || []), ...services.map((service) => service.category).filter(Boolean), ...items.map((item) => item.category).filter(Boolean)])], [workspace.inventoryCategories, services, items]);
  const filtered = useMemo(() => items.filter((item) => (category === 'All' || item.category === category) && [item.name, item.sku, item.category].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [items, category, query]);
  const save = async (form) => { setError(''); if (!form.category) return setError('Choose or enter an item category that matches your company offers.'); try { if (editing) await api.put(`/inventory/${editing._id}`, form); else await api.post('/inventory', form); setEditing(null); await load(); } catch (requestError) { setError(requestError.message); } };
  const changeQuantity = async (item, delta) => { try { await api.put(`/inventory/${item._id}`, { qty: Math.max(0, Number(item.qty ?? item.quantity ?? 0) + delta) }); await load(); } catch (requestError) { setError(requestError.message); } };
  const remove = async (item) => { if (!window.confirm(`Delete “${item.name}” from this company inventory?`)) return; try { await api.del(`/inventory/${item._id}`); await load(); } catch (requestError) { setError(requestError.message); } };
  return <CompanyShell title={workspace.inventoryLabel || 'Inventory'} subtitle="Only this company’s stock and business-specific item categories appear here." search={query} onSearch={setQuery} actions={<button onClick={() => setEditing({ isNew: true })} className="rounded-2xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white shadow-sm hover:bg-blue-700"><span className="material-symbols-outlined mr-1 align-middle text-base">add</span>Add item</button>}>
    {error && <p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <section className="mb-6 rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-sm font-semibold text-slate-500">Item categories are based on <b className="text-slate-900">{workspace.businessCategoryLabel || 'your company type'}</b> and your published offers.</p><div className="mt-4 flex flex-wrap gap-2">{['All', ...categoryOptions].map((value) => <button key={value} onClick={() => setCategory(value)} className={`rounded-full px-4 py-2 text-xs font-bold ${category === value ? 'bg-[#0D1B2A] text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>{value}</button>)}</div></section>
    <section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Item</th><th className="p-4">Category</th><th className="p-4">Stock</th><th className="p-4">Price</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item) => <tr key={item._id}><td className="p-4 font-bold text-slate-900">{item.name}<small className="mt-1 block font-mono font-medium text-slate-400">{item.sku}</small></td><td className="p-4 text-slate-600">{item.category}</td><td className="p-4 text-slate-700">{item.qty ?? item.quantity} {item.unit}<small className="block text-slate-400">Alert at {item.threshold ?? item.reorderLevel}</small></td><td className="p-4 font-semibold text-slate-900">{money(item.unitPrice)}</td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => changeQuantity(item, -1)} className="rounded-lg bg-slate-100 px-2 py-1 font-bold">−</button><button onClick={() => changeQuantity(item, 1)} className="rounded-lg bg-slate-100 px-2 py-1 font-bold">+</button><button onClick={() => setEditing(item)} className="rounded-lg px-2 py-1 text-blue-700 hover:bg-blue-50">Edit</button><button onClick={() => remove(item)} className="rounded-lg px-2 py-1 text-rose-600 hover:bg-rose-50">Delete</button></div></td></tr>)}{!filtered.length && <tr><td colSpan="5" className="p-12 text-center text-slate-500">No items match this company category yet.</td></tr>}</tbody></table></div></section>
    {editing && <ItemDialog item={editing.isNew ? null : editing} categories={categoryOptions} workspace={workspace} onClose={() => setEditing(null)} onSave={save} />}
  </CompanyShell>;
}
