import { useCallback, useEffect, useMemo, useState } from 'react';
import CompanyShell from '../../../components/company/CompanyShell';
import api from '../../../services/api';

const blank = () => ({ name: '', role: '', phone: '', email: '', experienceYears: 0, status: 'Available', avatar: '' });
function initials(name) { return String(name || 'ST').split(' ').map((part) => part[0]).slice(0, 2).join('').toUpperCase(); }

export default function CompanyTechnicians() {
  const [people, setPeople] = useState([]); const [company, setCompany] = useState(null); const [query, setQuery] = useState(''); const [error, setError] = useState('');
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState(null); const [form, setForm] = useState(blank());
  const load = useCallback(async () => { try { const [staffResult, dashboardResult] = await Promise.all([api.get('/technicians', { noCache: true }), api.get('/company/dashboard', { noCache: true })]); setPeople(staffResult.technicians || []); setCompany(dashboardResult.company || null); } catch (requestError) { setError(requestError.message); } }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  const staffLabel = company?.workspace?.workforceLabel || 'Staff'; const singular = staffLabel.endsWith('s') ? staffLabel.slice(0, -1) : staffLabel;
  const filtered = useMemo(() => people.filter((person) => [person.name, person.role, person.email, person.phone].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [people, query]);
  const close = () => { setOpen(false); setEditing(null); setForm(blank()); };
  const save = async (event) => { event.preventDefault(); try { if (editing) await api.put(`/technicians/${editing._id}`, form); else await api.post('/technicians', form); close(); await load(); } catch (requestError) { setError(requestError.message); } };
  const remove = async (person) => { if (!window.confirm(`Delete ${person.name}? Assigned staff cannot be deleted until their active work is reassigned.`)) return; try { await api.del(`/technicians/${person._id}`); await load(); } catch (requestError) { setError(requestError.message); } };
  const readAvatar = (event) => { const file = event.target.files?.[0]; if (!file) return; if (!file.type.startsWith('image/') || file.size > 1.5 * 1024 * 1024) return setError('Choose an image smaller than 1.5 MB.'); const reader = new FileReader(); reader.onload = () => setForm((current) => ({ ...current, avatar: reader.result })); reader.readAsDataURL(file); };
  return <CompanyShell title={staffLabel} subtitle={`Manage the ${staffLabel.toLowerCase()} who represent this company. Labels adapt to your company category.`} search={query} onSearch={setQuery} actions={<button onClick={() => { setEditing(null); setForm(blank()); setOpen(true); }} className="rounded-2xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Add {singular}</button>}>
    {error && <p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <section className="grid gap-5 md:grid-cols-2 xl:grid-cols-3">{filtered.map((person) => <article key={person._id} className="rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><div className="flex gap-4"><div className="grid h-14 w-14 shrink-0 place-items-center overflow-hidden rounded-2xl bg-[#0D1B2A] font-bold text-white">{person.avatar ? <img src={person.avatar} alt={person.name} className="h-full w-full object-cover" /> : initials(person.name)}</div><div className="min-w-0"><h2 className="truncate font-bold text-slate-900">{person.name}</h2><p className="mt-1 text-sm text-slate-500">{person.role || singular}</p><span className={`mt-2 inline-block rounded-full px-2.5 py-1 text-xs font-bold ${person.status === 'Available' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600'}`}>{person.status}</span></div></div><div className="mt-5 border-t border-slate-100 pt-4 text-sm text-slate-500"><p>{person.email || 'No email added'}</p><p className="mt-1">{person.phone || 'No phone added'} · {person.experienceYears || 0} years</p></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => { setEditing(person); setForm({ ...person }); setOpen(true); }} className="rounded-xl bg-blue-50 px-3 py-2 text-xs font-bold text-blue-700">Edit</button><button onClick={() => remove(person)} className="rounded-xl px-3 py-2 text-xs font-bold text-rose-600 hover:bg-rose-50">Delete</button></div></article>)}{!filtered.length && <p className="rounded-3xl border border-dashed border-slate-200 bg-white p-10 text-center text-slate-500 md:col-span-2 xl:col-span-3">No {staffLabel.toLowerCase()} have been added for this company.</p>}</section>
    {open && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold text-slate-900">{editing ? `Edit ${singular}` : `Add ${singular}`}</h2><p className="mt-1 text-sm text-slate-500">A profile picture and details are saved with this company only.</p></div><button type="button" onClick={close} className="text-slate-400">✕</button></div><div className="grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold text-slate-700">Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Role / responsibility<input value={form.role} onChange={(event) => setForm({ ...form, role: event.target.value })} placeholder={`e.g. ${singular}`} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Phone<input value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Email<input type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Experience (years)<input type="number" min="0" value={form.experienceYears} onChange={(event) => setForm({ ...form, experienceYears: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Availability<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"><option>Available</option><option>On Job</option><option>Unavailable</option></select></label><label className="sm:col-span-2 text-sm font-bold text-slate-700">Profile photo<input type="file" accept="image/png,image/jpeg,image/webp" onChange={readAvatar} className="mt-1 block w-full rounded-xl border border-slate-200 p-3 font-normal" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl px-4 py-3 font-bold text-slate-600">Cancel</button><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Save {singular}</button></div></form></div>}
  </CompanyShell>;
}
