import { useCallback, useEffect, useMemo, useState } from 'react';
import CompanyShell from '../../../components/company/CompanyShell';
import api from '../../../services/api';

const blank = () => ({ name: '', category: '', price: 0, durationMinutes: 60, status: 'Active', description: '' });
const money = (value) => `PKR ${Number(value || 0).toLocaleString('en-PK')}`;

export default function CompanyServices() {
  const [services, setServices] = useState([]); const [company, setCompany] = useState(null); const [query, setQuery] = useState('');
  const [form, setForm] = useState(blank()); const [editing, setEditing] = useState(null); const [open, setOpen] = useState(false); const [error, setError] = useState('');
  const load = useCallback(async () => { try { const [serviceResult, dashboardResult] = await Promise.all([api.get('/services', { noCache: true }), api.get('/company/dashboard', { noCache: true })]); setServices(serviceResult.services || []); setCompany(dashboardResult.company || null); } catch (requestError) { setError(requestError.message); } }, []);
  useEffect(() => { const timer = window.setTimeout(load, 0); return () => window.clearTimeout(timer); }, [load]);
  const suggestions = useMemo(() => [...new Set([...(company?.workspace?.inventoryCategories || []), ...services.map((service) => service.category).filter(Boolean)])], [company, services]);
  const filtered = useMemo(() => services.filter((service) => [service.name, service.category, service.description].some((value) => String(value || '').toLowerCase().includes(query.toLowerCase()))), [services, query]);
  const close = () => { setOpen(false); setEditing(null); setForm(blank()); };
  const save = async (event) => { event.preventDefault(); try { if (editing) await api.put(`/services/${editing._id}`, form); else await api.post('/services', form); close(); await load(); } catch (requestError) { setError(requestError.message); } };
  const changeStatus = async (service) => { try { await api.put(`/services/${service._id}`, { status: service.status === 'Active' ? 'Inactive' : 'Active' }); await load(); } catch (requestError) { setError(requestError.message); } };
  const remove = async (service) => { if (!window.confirm(`Remove “${service.name}”? Existing bookings will keep their recorded snapshot.`)) return; try { await api.del(`/services/${service._id}`); await load(); } catch (requestError) { setError(requestError.message); } };
  const workspace = company?.workspace || {};
  return <CompanyShell title={workspace.offeringLabel || 'Services'} subtitle="Publish only the products, services, packages, and offers your company actually provides." search={query} onSearch={setQuery} actions={<button onClick={() => { setEditing(null); setForm({ ...blank(), category: suggestions[0] || '' }); setOpen(true); }} className="rounded-2xl bg-blue-600 px-4 py-2.5 text-sm font-bold text-white hover:bg-blue-700">Add offer</button>}>
    {error && <p className="mb-5 rounded-2xl border border-red-100 bg-red-50 p-4 text-sm font-semibold text-red-700">{error}</p>}
    <section className="mb-6 rounded-3xl border border-slate-100 bg-white p-5 shadow-sm"><p className="text-sm text-slate-600">Client search and item categories use the offers you publish here. Choose wording that represents your <b>{workspace.businessCategoryLabel || 'company'}</b>.</p></section>
    <section className="overflow-hidden rounded-3xl border border-slate-100 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-4">Offer</th><th className="p-4">Category</th><th className="p-4">Price</th><th className="p-4">Availability</th><th className="p-4 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((service) => <tr key={service._id}><td className="p-4"><b className="text-slate-900">{service.name}</b><small className="mt-1 block max-w-md text-slate-500">{service.description || 'No description added.'}</small></td><td className="p-4 text-slate-600">{service.category}</td><td className="p-4 font-bold text-slate-900">{money(service.price)}<small className="block font-normal text-slate-400">{service.durationMinutes} minutes</small></td><td className="p-4"><span className={`rounded-full px-3 py-1 text-xs font-bold ${service.status === 'Active' ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-500'}`}>{service.status}</span></td><td className="p-4"><div className="flex justify-end gap-2"><button onClick={() => { setEditing(service); setForm({ ...service }); setOpen(true); }} className="rounded-lg px-2 py-1 text-blue-700 hover:bg-blue-50">Edit</button><button onClick={() => changeStatus(service)} className="rounded-lg px-2 py-1 text-slate-600 hover:bg-slate-100">{service.status === 'Active' ? 'Hide' : 'Publish'}</button><button onClick={() => remove(service)} className="rounded-lg px-2 py-1 text-rose-600 hover:bg-rose-50">Delete</button></div></td></tr>)}{!filtered.length && <tr><td colSpan="5" className="p-12 text-center text-slate-500">No offers have been added for this company yet.</td></tr>}</tbody></table></div></section>
    {open && <div className="fixed inset-0 z-[70] grid place-items-center bg-slate-950/40 p-4"><form onSubmit={save} className="w-full max-w-xl rounded-3xl bg-white p-6 shadow-2xl"><div className="mb-5 flex justify-between"><div><h2 className="text-xl font-bold text-slate-900">{editing ? 'Edit offer' : 'Add an offer'}</h2><p className="mt-1 text-sm text-slate-500">This is what clients can discover and book.</p></div><button type="button" onClick={close} className="text-slate-400">✕</button></div><div className="grid gap-4 sm:grid-cols-2"><label className="sm:col-span-2 text-sm font-bold text-slate-700">Offer name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Category<input required list="company-categories" value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} placeholder="Your business category" className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /><datalist id="company-categories">{suggestions.map((value) => <option key={value} value={value} />)}</datalist></label><label className="text-sm font-bold text-slate-700">Price (PKR)<input type="number" min="0" required value={form.price} onChange={(event) => setForm({ ...form, price: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Duration (minutes)<input type="number" min="0" required value={form.durationMinutes} onChange={(event) => setForm({ ...form, durationMinutes: Number(event.target.value) })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" /></label><label className="text-sm font-bold text-slate-700">Availability<select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"><option>Active</option><option>Inactive</option></select></label><label className="sm:col-span-2 text-sm font-bold text-slate-700">Client description<textarea required value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal" rows="3" /></label></div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={close} className="rounded-xl px-4 py-3 font-bold text-slate-600">Cancel</button><button className="rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Save offer</button></div></form></div>}
  </CompanyShell>;
}
